# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Benjamin Bowman
tagline: "Benjamin Bowman's research webpage"
description: "Benjamin Bowman's research webpage.  Contains my current research interests, publications, contact information, and other professional information."

# baseurl: # the subpath of your site, e.g. /blog
# url: # the base hostname & protocol for your site
author: Benjamin Bowman

# Build settings
markdown: kramdown

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
